packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^22.10.2
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@upstash/ratelimit': ^2.0.8
  '@upstash/redis': ^1.36.1
  '@vitejs/plugin-react': ^5.0.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  hono: ^4.7.11
  react: 19.2.0
  react-dom: 19.2.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.0.6
  together-ai: ^0.22.0
  tw-animate-css: ^1.4.0
  typescript: ^5.7.2
  vite: 7.3.1
  zod: ^4.1.5

onlyBuiltDependencies:
  - esbuild
  - lzo
  - msw
  - unrs-resolver
